name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Enforce merge review for main branch
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Please ensure that all changes are reviewed before merging into the master branch."
          exit 1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check Commit Message and Build Docker image
        if: contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE') || github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
        run: |
          echo "Building the Docker image..."
          docker build -t rahulgangwar8954/guestbook-go:latest .
          docker push rahulgangwar8954/guestbook-go:latest
