name: Build and Push Docker image to Docker Hub

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: rahulgangwar8954/guestbook-go:latest

      - name: Check Commit Message and Share GitHub Repo Link
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"BUILD_CONTAINER_IMAGE"* ]]; then
            echo "BUILD_CONTAINER_IMAGE string found in commit message. Proceeding to share the link."
            REPO_URL=$(git config --get remote.origin.url)
            echo "Repository URL: $REPO_URL"
            # Add your code here to send the link via email, e.g., use a command-line email client like 'mailx' or 'sendmail'
          else
            echo "No 'BUILD_CONTAINER_IMAGE' string found in commit message. Skipping sharing the link."
          fi
